# mkdocs.yml
site_name: OptiView Documentation
site_description: Database, engine, and maintenance documentation for OptiView.
site_author: 512jay
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.action.edit

docs_dir: docs

nav:
  - Home: index.md
  - Developer Notes:
      - Project Structure: dev_notes/project_structure.md
      - Database Schema: dev_notes/optiview_schema.md
      - (future) Architecture Overview: dev_notes/architecture_overview.md
  - User Guide:
      - Theory & Setup: user_guide/theory_and_setup.md      
      - Running Bulk Predictions: user_guide/bulk_predict.md
      - Maintenance Tasks: user_guide/maintenance.md
