"""Add synced_jobs table

Revision ID: 17e405df967f
Revises: c601aadfc9d1
Create Date: 2025-04-27 20:50:22.549786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e405df967f'
down_revision: Union[str, None] = 'c601aadfc9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synced_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expert_name', sa.String(), nullable=False),
    sa.Column('expert_path', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('leverage', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('optimization_mode', sa.String(), nullable=True),
    sa.Column('optimization_criterion', sa.String(), nullable=True),
    sa.Column('tester_inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synced_jobs')
    # ### end Alembic commands ###
