"""Initial database schema

Revision ID: 30dd7ec0b96a
Revises: 
Create Date: 2025-04-27 02:10:37.500646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dd7ec0b96a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluated_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('xgb', 'rf', 'gbr', 'histgb', 'lgbm', 'cat', name='modeltype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_stars', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted_settings',
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('xgb', 'rf', 'gbr', 'histgb', 'lgbm', 'cat', name='modeltype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('predicted_profit', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('expert_name', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('month', 'symbol', 'model', 'rank')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predicted_settings')
    op.drop_table('evaluated_settings')
    # ### end Alembic commands ###
