"""Add tuning_settings table

Revision ID: 3fa2c8111cbe
Revises: c14cd3dbed5f
Create Date: 2025-04-29 02:41:30.397120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa2c8111cbe'
down_revision: Union[str, None] = 'c14cd3dbed5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuning_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('confidence_settings_json', sa.String(), nullable=False),
    sa.Column('evaluation_settings_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuning_settings')
    # ### end Alembic commands ###
