"""Add evaluated_settings and predicted_settings

Revision ID: 8b3b24072caa
Revises: bec65ff74ae3
Create Date: 2025-04-26 21:07:29.630599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8b3b24072caa'
down_revision: Union[str, None] = 'bec65ff74ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluated_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('xgb', 'rf', 'gbr', 'histgb', 'lgbm', 'cat', name='modeltype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_stars', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicted_settings',
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('xgb', 'rf', 'gbr', 'histgb', 'lgbm', 'cat', name='modeltype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('predicted_profit', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('expert_name', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('month', 'symbol', 'model', 'rank')
    )
    op.drop_table('predicted_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predicted_configs',
    sa.Column('month', sa.VARCHAR(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=6), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('predicted_profit', sa.FLOAT(), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('confidence_stars', sa.VARCHAR(), nullable=True),
    sa.Column('actual_profit', sa.FLOAT(), nullable=True),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('quality_stars', sa.VARCHAR(), nullable=True),
    sa.Column('expert_name', sa.VARCHAR(), nullable=True),
    sa.Column('inputs', sqlite.JSON(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('month', 'symbol', 'model', 'rank')
    )
    op.drop_table('predicted_settings')
    op.drop_table('evaluated_settings')
    # ### end Alembic commands ###
