"""initial schema

Revision ID: 94843f39e513
Revises: 
Create Date: 2025-04-30 03:43:59.758835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94843f39e513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluated_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('evaluator_version', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_stars', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('actual_result', sa.Float(), nullable=True),
    sa.Column('predicted_profit', sa.Float(), nullable=True),
    sa.Column('matched_run_id', sa.Integer(), nullable=True),
    sa.Column('matched_job_id', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'symbol', 'model', 'rank', 'evaluator_version', name='uq_evaluated_config_versioned')
    )
    op.create_table('predicted_settings',
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('xgb', 'rf', 'gbr', 'histgb', 'lgbm', 'cat', name='modeltype'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('predicted_profit', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_stars', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('month', 'symbol', 'model', 'rank')
    )
    op.create_table('synced_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expert_name', sa.String(), nullable=False),
    sa.Column('expert_path', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('leverage', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('optimization_mode', sa.String(), nullable=True),
    sa.Column('optimization_criterion', sa.String(), nullable=True),
    sa.Column('tester_inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('confidence_settings_json', sa.Text(), nullable=False),
    sa.Column('evaluation_settings_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tuning_settings')
    op.drop_table('synced_jobs')
    op.drop_table('predicted_settings')
    op.drop_table('evaluated_settings')
    # ### end Alembic commands ###
