"""Remove expert_advisor from PredictedSetting

Revision ID: c14cd3dbed5f
Revises: 17e405df967f
Create Date: 2025-04-28 04:53:43.024858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14cd3dbed5f'
down_revision: Union[str, None] = '17e405df967f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_settings', 'expert_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_settings', sa.Column('expert_name', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
