"""Add params_json to predicted_settings

Revision ID: c601aadfc9d1
Revises: 30dd7ec0b96a
Create Date: 2025-04-27 12:21:39.021228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c601aadfc9d1'
down_revision: Union[str, None] = '30dd7ec0b96a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predicted_settings', sa.Column('params_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predicted_settings', 'params_json')
    # ### end Alembic commands ###
